### PR TITLE
Android and iOS use different http client

### PR DESCRIPTION
**Pull request by Trivias91**
This fixes a problem I saw in iOS where the http client was causing a small memory leak in that two Mono.Net.Security.BufferOffsetSize2 Objects were created each time analytics were sent and would not be cleaned up. The fix is simply using the modern http client package for the http client on Android and iOS.  

Signed-off-by: tsauder <tsauder@gowithfloat.com>

### CODE REVIEW

**Comment by KSemenenko** [comment]
Thanks for your work, I will update tomorrow nuget!

**Comment by ncruces** [comment]
@KSemenenko I'm in the process of removing the ModernHttpClient from my dependency tree, so this change is unfortunate for me.

Xamarin on both iOS and Android [now](https://developer.xamarin.com/guides/cross-platform/transport-layer-security/#HttpClient) supports using the platform's HTTP implementations without the need for ModernHttpClient.

@Trivias91, I'd like to understand the settings you were using on iOS when you detected this issue. Were you using either one of `CFNetworkHandler `/`NSUrlSessionHandler`?

**Comment by KSemenenko** [comment]
@ncruces will you make pull request?

**Comment by ncruces** [comment]
I could. I'd just be reverting this one though? There's nothing to do at the library level. On the Android/iOS projects you can configure Xamarin to use the native `HttpMessageHandler`.

I'd still like some feedback from @Trivias91. I don't have any issues with those in my app, but he might have found a legitimate bug.

**Comment by KSemenenko** [comment]
@Trivias91 any updates?

**Comment by Trivias91** [comment]
Hi, Sorry i haven't responded; I've been on vacation.  I do not remember what my configuration was.  I don't believe it was changed from the default though.

**Comment by ncruces** [comment]
@Trivias91, the Xamarin default is to use the managed versions, for best compatibility with .NET.

In any case, it probably makes sense to use the same HTTP stack across your entire app. If you're using ModernHttpClient elsewhere in your app, it makes sense for you to use it here too. I'm going the other way: cutting a dependency and using the native Xamarin stack all the way. To make us both happy, we'd need to be able to pick the used `HttpMessageHandler` (something other libraries do).

I haven't looked deep into the code to see how I might achieve this. I see you're creating and disposing of handlers for every dispatch. In principle this is unnecessary, and a single handler provided by the app can be reused. Also this isn't wasteful, because the entire app can share a single handler (`HttpMessageHandler` is [thread safe](https://msdn.microsoft.com/en-us/library/system.net.http.httpmessagehandler(v=vs.110).aspx)).

@KSemenenko, I don't mind having a go at this, but I'd like your feedback before proceeding. Making the `HttpMessageHandler` configurable, would that work for you? Where do you envision I would provide the `HttpMessageHandler` instance/factory to be used?

**Comment by KSemenenko** [comment]
I deleted the ModernHttpClient, and make a new build.

**Pull request merged**
